[env:featheresp32]
platform = espressif32
board = featheresp32
framework = arduino
lib_deps =
    adafruit/Adafruit ST7735 and ST7789 Library
    adafruit/Adafruit GFX Library
    bblanchon/ArduinoJson @ ^7.0.0
    arduino-libraries/NTPClient
    adafruit/Adafruit BusIO
monitor_speed = 115200
build_flags =
    -DCORE_DEBUG_LEVEL=1
