[env:featheresp32]
platform = espressif32
board = featheresp32
framework = arduino
lib_deps =
    adafruit/Adafruit ST7735 and ST7789 Library
    adafruit/Adafruit GFX Library
    bblanchon/ArduinoJson @ ^7.0.0
    arduino-libraries/NTPClient
    adafruit/Adafruit BusIO
    tzapu/WiFiManager 
monitor_speed = 115200
board_build.partitions = min_spiffs.csv
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -Os
