#!/usr/bin/env python3
"""
Generate 16x16 GB2312-80 dot-matrix font data using WenQuanYi Bitmap Song 16px.
Output format matches the original gb2312_font.h exactly.
Usage: python gen_gb2312_font_16.py [--font FONT_PATH] [--font-size N]
"""

import os
import sys
import time
from PIL import Image, ImageDraw, ImageFont

FONT_PATH = os.path.join(os.path.dirname(__file__), "wqy-bitmap-song-16px.ttf")
FONT_SIZE = 16
GLYPH_SIZE = 16

def iter_gb2312_chars():
    for row in range(1, 95):
        for col in range(1, 95):
            gb_bytes = bytes([0xA0 + row, 0xA0 + col])
            try:
                char = gb_bytes.decode('gb2312')
                yield (ord(char), char)
            except UnicodeDecodeError:
                pass

def render_glyph(char, font):
    img = Image.new('L', (GLYPH_SIZE, GLYPH_SIZE), 255)
    draw = ImageDraw.Draw(img)

    bbox = draw.textbbox((0, 0), char, font=font)
    char_w = bbox[2] - bbox[0]
    char_h = bbox[3] - bbox[1]

    x_offset = (GLYPH_SIZE - char_w) // 2 - bbox[0]
    y_offset = (GLYPH_SIZE - char_h) // 2 - bbox[1]
    draw.text((x_offset, y_offset), char, font=font, fill=0)

    pixels = list(img.getdata())
    glyph = bytearray()
    for row in range(GLYPH_SIZE):
        bits = 0
        for col in range(GLYPH_SIZE):
            if pixels[row * GLYPH_SIZE + col] < 128:
                bits |= (1 << (15 - col))
        glyph.append((bits >> 8) & 0xFF)
        glyph.append(bits & 0xFF)
    return bytes(glyph)

def write_header(out, chars, glyph_data, map_entries):
    w = lambda s: out.write(s + "\n")

    w("// Auto-generated by tools/gen_gb2312_font_16.py")
    w("// GB2312-80 complete (Level 1 + Level 2 + Symbols), 16x16 dot matrix")
    w("// WenQuanYi Micro Hei font")
    w(f"// {len(chars)} characters, {len(glyph_data)} bytes glyph data")
    w("#pragma once")
    w("#include <Arduino.h>")
    w("#include <pgmspace.h>")
    w("")
    w("// Glyph data: each entry is 32 bytes (16 rows x uint16_t)")
    w(f"static const uint8_t gb2312_glyph_data[{len(glyph_data)}] PROGMEM = {{")
    for i in range(0, len(glyph_data), 16):
        chunk = glyph_data[i:i+16]
        hex_str = ", ".join(f"0x{b:02X}" for b in chunk)
        w(f"  {hex_str},")
    w("};")
    w("")

    w("struct GBMapEntry { uint16_t unicode; uint16_t idx; };")
    w(f"static const GBMapEntry gb2312_map[{len(map_entries)}] PROGMEM = {{")
    for u, idx in map_entries:
        w(f"  {{0x{u:04X}, {idx}}},")
    w("};")
    w("")

    w("inline const uint8_t* findGB2312Glyph(uint16_t unicode) {")
    w(f"  int lo = 0, hi = {len(chars)} - 1;")
    w("  while (lo <= hi) {")
    w("    int mid = (lo + hi) / 2;")
    w("    uint16_t u = pgm_read_word(&gb2312_map[mid].unicode);")
    w("    if (u == unicode) {")
    w("      uint16_t idx = pgm_read_word(&gb2312_map[mid].idx);")
    w("      return &gb2312_glyph_data[idx * 32];")
    w("    }")
    w("    if (u < unicode) lo = mid + 1;")
    w("    else hi = mid - 1;")
    w("  }")
    w("  return nullptr;")
    w("}")
    w("")

    w("inline uint16_t utf8ToUnicode(const char **p) {")
    w("  uint8_t b0 = (uint8_t)(*p)[0];")
    w("  if (b0 < 0x80) { (*p)++; return b0; }")
    w("  if ((b0 & 0xE0) == 0xC0) {")
    w("    uint16_t c = ((uint16_t)(b0 & 0x1F) << 6) | ((uint8_t)(*p)[1] & 0x3F);")
    w("    (*p) += 2; return c;")
    w("  }")
    w("  if ((b0 & 0xF0) == 0xE0) {")
    w("    uint16_t c = ((uint16_t)(b0 & 0x0F) << 12)")
    w("               | ((uint16_t)((*p)[1] & 0x3F) << 6)")
    w("               | ((*p)[2] & 0x3F);")
    w("    (*p) += 3; return c;")
    w("  }")
    w("  (*p)++; return 0;")
    w("}")
    w("")

    w("// Draw GB2312 text at (x, y) using the 16px dot-matrix font.")
    w("// Each CJK character is 16px wide. ASCII chars are 8px wide.")
    w("// Line breaks at '\\n'.")
    w("inline void drawGB16(int x, int y, const char *text, uint16_t fg, uint16_t bg) {")
    w("  int origX = x;")
    w("  while (*text) {")
    w("    if (*text == '\\n') { x = origX; y += 20; text++; continue; }")
    w("    uint16_t uc = utf8ToUnicode(&text);")
    w("    if (uc < 0x80) {")
    w("      tft->setTextSize(1);")
    w("      tft->setTextColor(fg, bg);")
    w("      tft->setCursor(x, y + 4);")
    w("      tft->print((char)uc);")
    w("      x += 8;")
    w("      continue;")
    w("    }")
    w("    if (uc < 0x4E00 || uc > 0x9FFF) {")
    w("      bool allowed =")
    w("        (uc >= 0x3000 && uc <= 0x303F) ||")
    w("        (uc >= 0xFF00 && uc <= 0xFFEF) ||")
    w("        (uc >= 0x2000 && uc <= 0x206F) ||")
    w("        (uc >= 0x2100 && uc <= 0x214F) ||")
    w("        (uc >= 0xFE30 && uc <= 0xFE4F);")
    w("      if (!allowed) continue;")
    w("    }")
    w("    const uint8_t *g = findGB2312Glyph(uc);")
    w("    if (!g) { x += 16; continue; }")
    w("    tft->startWrite();")
    w("    for (int row = 0; row < 16; row++) {")
    w("      uint16_t bits = ((uint16_t)pgm_read_byte(&g[row * 2]) << 8)")
    w("                     | pgm_read_byte(&g[row * 2 + 1]);")
    w("      for (int col = 0; col < 16; col++) {")
    w("        if (bits & (0x8000 >> col)) {")
    w("          tft->writePixel(x + col, y + row, fg);")
    w("        }")
    w("      }")
    w("    }")
    w("    tft->endWrite();")
    w("    x += 16;")
    w("  }")
    w("}")

def main():
    font_path = FONT_PATH
    font_size = FONT_SIZE

    for arg in sys.argv[1:]:
        if arg.startswith("--font="):
            font_path = arg.split("=", 1)[1]
        elif arg.startswith("--font-size="):
            font_size = int(arg.split("=", 1)[1])

    if not os.path.exists(font_path):
        print(f"Error: Font not found at {font_path}", file=sys.stderr)
        sys.exit(1)

    print(f"Loading font: {font_path} (size={font_size})")
    font = ImageFont.truetype(font_path, font_size)

    print("Iterating GB2312-80 characters...")
    chars = sorted(iter_gb2312_chars(), key=lambda x: x[0])
    print(f"Found {len(chars)} characters")

    glyph_data = bytearray()
    map_entries = []
    total = len(chars)
    t0 = time.time()

    for idx, (u, char) in enumerate(chars):
        if idx % 500 == 0 or idx == total - 1:
            elapsed = time.time() - t0
            pct = (idx + 1) / total * 100
            rate = (idx + 1) / elapsed if elapsed > 0 else 0
            eta = (total - idx - 1) / rate if rate > 0 else 0
            print(f"  [{pct:5.1f}%] {idx+1}/{total} U+{u:04X} '{char}'  "
                  f"({rate:.0f} chars/s, ETA {eta:.0f}s)", end="\r" if idx < total-1 else "\n")
        glyph = render_glyph(char, font)
        glyph_data.extend(glyph)
        map_entries.append((u, idx))

    total_time = time.time() - t0
    print(f"Rendered {total} glyphs in {total_time:.1f}s "
          f"({total/total_time:.0f} chars/s)")
    print(f"Glyph data: {len(glyph_data)} bytes "
          f"({len(glyph_data)/1024:.0f} KB)")

    out_path = os.path.join(os.path.dirname(__file__), "..", "src", "gb2312_font.h")
    print(f"Writing {out_path} ...")
    with open(out_path, "w", encoding="utf-8") as f:
        write_header(f, chars, glyph_data, map_entries)

    file_size = os.path.getsize(out_path)
    print(f"Done! Output: {out_path} ({file_size/1024:.0f} KB on disk)")

if __name__ == "__main__":
    main()
